# Generated by Django 4.2.8 on 2024-07-08 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('filename_logo', models.CharField(max_length=100)),
                ('website_link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date_created', models.DateField()),
                ('date_deadline', models.DateField()),
                ('description', models.TextField()),
                ('is_finished', models.BooleanField()),
                ('is_started', models.BooleanField()),
                ('is_cancelled', models.BooleanField()),
                ('github_link', models.CharField(max_length=250, null=True)),
                ('lang_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ideas.language')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filename_logo', models.CharField(max_length=100)),
                ('website_link', models.CharField(max_length=255)),
                ('lang_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ideas.language')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ideas.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tech_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ideas.technology'),
        ),
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
