# Generated by Django 4.2.8 on 2024-07-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_remove_technology_lang_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='lang_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='screenshot',
            name='project_id',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Screenshot',
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
