# Generated by Django 4.2.8 on 2024-07-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='lang_id',
        ),
    ]
