# Generated by Django 4.2.8 on 2024-07-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_alter_language_filename_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='filename_logo',
            field=models.ImageField(upload_to='tech_logos/%y'),
        ),
    ]
